specVersion: 1.0.0
name: PolkaGate
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=1.0.0"
  query:
    name: "@subql/query"
    version: "*"
description: This project can be used to query kusama chain
repository: "https://github.com/Nick-1979/subquery/subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
  endpoint: "wss://kusama.api.onfinality.io/public-ws"
  dictionary: "https://api.subquery.network/sq/subquery/kusama-dictionary"
dataSources:
  - kind: substrate/Runtime
    startBlock: 11801246
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleVouche
          kind: substrate/EventHandler
          filter:
            module: recovery
            method: RecoveryVouched
        - handler: handleInitiation
          kind: substrate/EventHandler
          filter:
            module: recovery
            method: RecoveryInitiated
        - handler: handleClose
          kind: substrate/EventHandler
          filter:
            module: recovery
            method: RecoveryClosed
